### ISSUE TITLE
Upload apk

### ISSUE THREAD

**Issue by xuan2261** [QuynhVir/Bypass-Facebook-SSL-Pinning#1]
Bạn có thể upload file apk Facebook for Android version 210.0.0.43.119 x86 lên được không. mình tải mấy file apk trên mạng về cài rồi bỏ path của bạn vào thì toàn bị lỗi mạng.

**Comment by QuynhVir** [comment]
Thiết bị thử k phải của mình, mình cũng không còn máy Android nào.
Cái bypass này không còn nhiều ý nghĩa nữa từ khi Facebook cho phép bypass qua cài đặt Whitehat cho researcher.
Bạn có thể xem ở đây: https://www.facebook.com/whitehat/researcher-settings/
Sau khi bật trên Facebook thì bật trong app nữa là được.
